# Site settings
title: very nomagic
fullname: Pedro Araujo
author:
    twitter: phcrva
#job: SRE
#email: <email>
description: Musings on vim, distributed systems, monitoring, OS X, Linux and misc.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter:
  username: phcrva
github_username:  pharaujo

permalink: /:year/:month/:title.html

# Build settings
#markdown: redcarpet
markdown: kramdown
kramdown:
    input: GFM
#highlighter: pygments

safe: true
lsi: false

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.markdown"]
include: [".well-known"]

gems:
    - jekyll-seo-tag
    - jekyll-sitemap

whitelist:
    - jekyll-seo-tag
    - jekyll-sitemap
